"""empty message

Revision ID: 332f5c7d413e
Revises: 59169fdb5251
Create Date: 2021-08-19 03:00:24.856032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332f5c7d413e'
down_revision = '59169fdb5251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category', sa.String(length=255), nullable=False))
    op.drop_column('post_child', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_child', sa.Column('category', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('post', 'category')
    # ### end Alembic commands ###
