"""empty message

Revision ID: 59169fdb5251
Revises: a0340cc4955b
Create Date: 2021-08-18 01:14:10.668736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59169fdb5251'
down_revision = 'a0340cc4955b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_child', sa.Column('lat', sa.Integer(), nullable=False))
    op.add_column('post_child', sa.Column('lng', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_child', 'lng')
    op.drop_column('post_child', 'lat')
    # ### end Alembic commands ###
