"""empty message

Revision ID: 7dbe2f1919ee
Revises: 00c704106d14
Create Date: 2021-08-19 03:10:21.202570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbe2f1919ee'
down_revision = '00c704106d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category', sa.String(length=255), nullable=True))
    op.drop_column('post_child', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_child', sa.Column('category', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('post', 'category')
    # ### end Alembic commands ###
