"""empty message

Revision ID: a0340cc4955b
Revises: 025d33524465
Create Date: 2021-08-17 23:26:37.979053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0340cc4955b'
down_revision = '025d33524465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_child', sa.Column('num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_child', 'num')
    # ### end Alembic commands ###
